### PR TITLE
Issue #10

### LINKED ISSUE #10: [FEATURE] Create Social links container for Edit Panel of SocialRepo
# Create links container using `HTML/CSS` for **Edit Panel**

## Description
Create the social links container as provided in the below image:
Untitled - Design1 - Social Repo (another copy)

## Code
- Use `HTML/CSS` for creating and designing the container.
- Must follow the [**Code Guidelines**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#code-guidelines) provided.
- Each container should be a list item (`li`) as a part of unordered list (`ul`) element.
- The unordered list (`ul`) element should be inside the **edit** section in `HTML`.
	```html
	<section id="edit">
	    <h2>Edit Panel</h2>
	</section>
	```
- To test the code, setup the extension by following [these](https://github.com/Param302/SocialRepo/blob/main/.github/docs/CONTRIBUTING.md#extension-setup) steps.
- Use the [**Color Palette**](https://github.com/Param302/SocialRepo/blob/main/.github/docs/README.md#color-theme) provided. You can add a light purple color as the background of container.
- Don't use favicons for arrow, rather download the relevant **png** arrow icon and store it in [`logos`](https://github.com/Param302/SocialRepo/tree/main/src/assets/logos) folder.
- The icon must not be more than `256x256` pixels.

### Additional
- Apply focus, hover effect.
- Replicate the containers to get visual appeal.
- Implement Scrollbar for Y-axis.

> **P.S**: This is just the designing part, no need to add any functionality as of now.

If you have any suggestion or idea, you're welcome to share.

_Let's design the SocialRepo social links container_ 🙌

### PR DESCRIPTION
**Pull request by Abhinavpatra**
# Title
Fix issue with social links container in Edit Panel

## Description
Resolved the issue with the social links container not being displayed properly in the Edit Panel section. Added the necessary HTML and CSS to create the social links container inside the Edit Panel. The container now displays social media icons with proper spacing and hover effects.

Dependencies: None

---
## Issue Ticket Number
Fixes #10 

---
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING](./docs/CONTRIBUTING)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Param302/SocialRepo/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Review by Param302 — CHANGES_REQUESTED** [review]
Hey @Abhinavpatra ,

It's good to see that you've fixed the bugs and improved the code.
Now I can see the links, but still it's not same as the design I proposed, like the width of container should be full.

Please do the necessary changes, rest I will handle and merge!

_Thanks for contributing to **SocialRepo**_

## Reference

### Expected output
Untitled - Design1 - Social Repo (copy)


### Your output
image

**Comment by Param302** [comment]
I saw your enthusiasm, so I am assigning you the issue.
You can completely work on it!

Cheers!

**Comment by Abhinavpatra** [comment]
image
thanks for assigning it, i actually came accross this project on gssoc'24 so made the contribution for that, does this look as you asked, if so you can merge my PR.

**Review by Param302 — CHANGES_REQUESTED** [review]
Hey @Abhinavpatra ,

The changes you've made are good, but it added a bug as well.
The Edit panel is being shown in all other panels as well.
Please fix it.

## Output
image

**Comment by Abhinavpatra** [comment]
the edit panel was always visible, just prior to my addition it was just that the content inside the section, was empty, i will need to edit the js i think, in order to fix this issue,

**Comment by Param302** [comment]
> the edit panel was always visible, just prior to my addition it was just that the content inside the section, was empty, i will need to edit the js i think, in order to fix this issue,

oky, you closed this PR 😅
yes, fetch the latest code and fix your issue, and do a new PR.

**Pull request closed without merging**
