### PR TITLE
Updated URL formats for 7 platforms in socials.json

### LINKED ISSUE #2: [FEATURE] Social media profile URLs
## Description
Adding social media profile URLs in [`social-links.json`](https://github.com/Param302/SocialRepo/blob/main/src/social-links.json) in **Alphabetical order**.
Also, check the social media or add new ones in [`social-apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md)

## Social media list
The list of social media apps/website which has *public user profile* feature is present in [`social-apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md)

You can choose any 7 social media names which are not added in [`social-links.json`](https://github.com/Param302/SocialRepo/blob/main/src/social-links.json).

Make sure to **NOT** to choose the apps which are already done.
Example: _LinkedIn, Github & Medium are already done_

### How to verify ❓
- The social media names are checked in  [`social-apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md)
- The same social media profile URLs are present in [`social-links.json`](https://github.com/Param302/SocialRepo/blob/main/src/social-links.json)

_Please feel free to recommend and more apps which has social (public) user profile system._

## Style
```json
{
    "social_media_name": "link",
    "linkedin": "https://www.linkedin.com/in/<username>",
    "github": "https://www.github.com/<username>",
    "medium": "https://<username>.medium.com"
}
```
_Let's create the user life easier by listing all social media platforms._

### PR DESCRIPTION
**Pull request by SamFusedBits**
# Title
Updated URL formats for 7 platforms in socials.json

## Description
Added new user profile URL formats for Airchat, Bio.link, Dev.to, Fiverr, Hashnode, Leetcode, and Upwork in the miscellaneous section of socials.json.

---
## Issue Ticket Number
Fixes #2 

---
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---
# Checklist:
- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING](./docs/CONTRIBUTING)
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/Param302/SocialRepo/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes needed to the documentation

### CODE REVIEW

**Comment by Param302** [comment]
Hey @SamFusedBits ,
Thanks for contributing!

Please also check/add the names in [`social-apps.md`](https://github.com/Param302/SocialRepo/blob/main/.github/docs/social-apps.md) to keep a track, then I will merge it.

**Comment by Param302** [comment]
Hey @SamFusedBits ,
I saw you've opened this new PR for the same issue #2 so, I am closing your old #11  PR.

**Review by Param302 — CHANGES_REQUESTED** [review]
Hey,
Let me know when you check/add the handle names `social-apps.md`, I will merge the PR.

Thanks

**Comment by SamFusedBits** [comment]
Hi @Param302,

I've updated the `social-apps.md` file with the names of the 7 social platforms I've worked on, as requested.

**Comment by Param302** [comment]
> Hi @Param302,
> 
> I've updated the `social-apps.md` file with the names of the 7 social platforms I've worked on, as requested.

Hey @SamFusedBits ,
You have closed the PR.
Either reopen it or create a new one.

**Pull request closed without merging**
